"""add user_id and client_ip to kyc_transactions

Revision ID: ccf2472a6066
Revises: b1fe298d90b1
Create Date: 2026-03-21 19:50:47.424790

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ccf2472a6066'
down_revision: Union[str, Sequence[str], None] = 'b1fe298d90b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kyc_transactions', sa.Column('user_id', sa.Integer(), nullable=True))
    op.add_column('kyc_transactions', sa.Column('client_ip', sa.String(), nullable=True))
    op.create_index(op.f('ix_kyc_transactions_user_id'), 'kyc_transactions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_kyc_transactions_user_id'), table_name='kyc_transactions')
    op.drop_column('kyc_transactions', 'client_ip')
    op.drop_column('kyc_transactions', 'user_id')
    # ### end Alembic commands ###
